user_ivan = User.create!(name: "Иван")
user_maga = User.create!(name: "Мага")
user_ruslan = User.create(name: "Руслан")
p "Created #{User.count} Users"

logical_category = Category.create!(title: "Логические")
academic_category = Category.create!(title: "Академические")
p "Created #{User.count} Users"

history_test1 = Test.create!(title: "История", level: "1", author_id: user_maga.id, category_id: academic_category.id)
history_test2 = Test.create!(title: "История", level: "1", author_id: user_maga.id, category_id: academic_category.id)
geography_test1 = Test.create!(title: "География", level: "1", author_id: user_ruslan.id, category_id: academic_category.id)
geography_test2 = Test.create!(title: "География", level: "2", author_id: user_ruslan.id, category_id: academic_category.id)
logical_test1 = Test.create!(title: "Логика", level: "1", author_id: user_ivan.id, category_id: logical_category.id)
logical_test2 = Test.create!(title: "Логика", level: "2", author_id: user_ivan.id, category_id: logical_category.id)
p "Created #{Test.count} Tests"

history_question1 = Question.create!(body: "Первый президент России", test_id: history_test1.id)
history_question2 = Question.create!(body: "Год распада СССР", test_id: history_test1.id)
history_question3 = Question.create!(body: "Какой город стал столицей Древнерусского государства?", test_id: history_test1.id)
history_question4 = Question.create!(body: "В каком городе находится самый крупный музей России — Эрмитаж?", test_id: history_test2.id)
history_question5 = Question.create!(body: "Когда в России отменили крепостное право?", test_id: history_test2.id)
history_question6 = Question.create!(body: "Кем был П.И. Чайковский?", test_id: history_test2.id)
geography_question1 = Question.create!(body: "Самая большая страна в мире", test_id: geography_test1.id)
geography_question2 = Question.create!(body: "Сколько часовых поясов в России?", test_id: geography_test1.id)
geography_question3 = Question.create!(body: "Какое море омывает берега Италии?", test_id: geography_test1.id)
geography_question4 = Question.create!(body: "Самое маленькое государство в Европе", test_id: geography_test2.id)
geography_question5 = Question.create!(body: "Как называется самый известный водопад в Канаде?", test_id: geography_test2.id)
geography_question6 = Question.create!(body: "Что такое муссон?", test_id: geography_test2.id)
logical_question1 = Question.create!(body: "Каких камней не бывает в речке?", test_id: logical_test1.id)
logical_question2 = Question.create!(body: "Что не вместится даже в самую большую кастрюлю?", test_id: logical_test1.id)
logical_question3 = Question.create!(body: "Что можно завязать, но нельзя развязать?", test_id: logical_test1.id)
p "Created #{Question.count} Questions"

Answer.create!(body: "Ельцин", correct: true, question_id: history_question1.id)
Answer.create!(body: "Путин", correct: false, question_id: history_question1.id)
Answer.create!(body: "Медведев", correct: false, question_id: history_question1.id)
Answer.create!(body: "1991", correct: true, question_id: history_question2.id)
Answer.create!(body: "1990", correct: false, question_id: history_question2.id)
Answer.create!(body: "1992", correct: false, question_id: history_question2.id)
Answer.create!(body: "Киев", correct: true, question_id: history_question3.id)
Answer.create!(body: "Москва", correct: false, question_id: history_question3.id)
Answer.create!(body: "Таганрог", correct: false, question_id: history_question3.id)
Answer.create!(body: "Санкт-Петербург", correct: true, question_id: history_question4.id)
Answer.create!(body: "Казань", correct: false, question_id: history_question4.id)
Answer.create!(body: "Екатеринбург", correct: false, question_id: history_question4.id)
Answer.create!(body: "1861", correct: true, question_id: history_question5.id)
Answer.create!(body: "1821", correct: false, question_id: history_question5.id)
Answer.create!(body: "1561", correct: false, question_id: history_question5.id)
Answer.create!(body: "Композитором", correct: true, question_id: history_question6.id)
Answer.create!(body: "Художником", correct: false, question_id: history_question6.id)
Answer.create!(body: "Писателем", correct: false, question_id: history_question6.id)
Answer.create!(body: "Россия", correct: true, question_id: geography_question1.id)
Answer.create!(body: "Канада", correct: false, question_id: geography_question1.id)
Answer.create!(body: "США", correct: false, question_id: geography_question1.id)
Answer.create!(body: "11", correct: true, question_id: geography_question2.id)
Answer.create!(body: "3", correct: false, question_id: geography_question2.id)
Answer.create!(body: "7", correct: false, question_id: geography_question2.id)
Answer.create!(body: "Средиземное", correct: true, question_id: geography_question3.id)
Answer.create!(body: "Черное", correct: false, question_id: geography_question3.id)
Answer.create!(body: "Красное", correct: false, question_id: geography_question3.id)
Answer.create!(body: "Ватикан", correct: true, question_id: geography_question4.id)
Answer.create!(body: "Мальта", correct: false, question_id: geography_question4.id)
Answer.create!(body: "Андорра", correct: false, question_id: geography_question4.id)
Answer.create!(body: "Ниагарский", correct: true, question_id: geography_question5.id)
Answer.create!(body: "Анхель", correct: false, question_id: geography_question5.id)
Answer.create!(body: "Виктория", correct: false, question_id: geography_question5.id)
Answer.create!(body: "Ветер", correct: true, question_id: geography_question6.id)
Answer.create!(body: "Течение", correct: false, question_id: geography_question6.id)
Answer.create!(body: "Тропический дождь", correct: false, question_id: geography_question6.id)
Answer.create!(body: "Сухих", correct: true, question_id: logical_question1.id)
Answer.create!(body: "Драгоценных", correct: false, question_id: logical_question1.id)
Answer.create!(body: "Больших", correct: false, question_id: logical_question1.id)
Answer.create!(body: "Ее крышка", correct: true, question_id: logical_question2.id)
Answer.create!(body: "Большая репа", correct: false, question_id: logical_question2.id)
Answer.create!(body: "Кочан капусты", correct: false, question_id: logical_question2.id)
Answer.create!(body: "Разговор", correct: true, question_id: logical_question3.id)
Answer.create!(body: "Шнурки", correct: false, question_id: logical_question3.id)
Answer.create!(body: "Наушники", correct: false, question_id: logical_question3.id)
p "Created #{Answer.count} Answers"

TestsUser.create(test_id: history_test1.id, user_id: user_ivan.id)
TestsUser.create(test_id: history_test2.id, user_id: user_ivan.id)
TestsUser.create(test_id: geography_test1.id, user_id: user_maga.id)
TestsUser.create(test_id: geography_test2.id, user_id: user_maga.id)
p "Created #{TestsUser.count} Answers"
